export const INDEX_ABOUT_SECTION = "/#about"
export const INDEX_AGENDA_SECTION = "/#agenda"
export const INDEX_SPEAKERS_SECTION = "/#speakers"
export const INDEX_CHALLENGES_SECTION = "/#challenges"
export const INDEX_SPONSORS_SECTION = "/#sponsors"
